### ISSUE TITLE
Retry for 503 API response

### ISSUE THREAD

**Issue by andryan** [jeremykenedy/slack#4]
Hello,

I noticed that Slack API sometimes responds with 503, would it be possible to implement a retry with something like https://github.com/caseyamcl/guzzle_retry_middleware or the native retry middleware in Guzzle?

Cheers,
Andryan

**Comment by jeremykenedy** [comment]
The events do not persist and retry. You can wrap it in a try/catch I suppose and action accordingly. That's how I have handled slack failures with app logging in the past.
